#!/usr/bin/env fish

set here (dirname (realpath (status filename)))
set dotfiles $here/dotfiles
ln -sf $dotfiles/config.fish ~/.config/fish/
rmdir ~/.config/fish/functions ^/dev/null
ln -sf $dotfiles/functions ~/.config/fish/ ^/dev/null
ln -sf $dotfiles/nanorc ~/.nanorc
ln -sf $dotfiles/sitecustomize.py ~/.local/lib/python3.7/
ln -sf $dotfiles/sitecustomize.py ~/.local/lib/python3.8/
