#!/usr/bin/env fish

set here (dirname (realpath (status filename)))
set dotfiles $here/dotfiles

ln -sf $dotfiles/config.fish ~/.config/fish/
rm -r ~/.config/fish/functions
ln -sf $dotfiles/functions ~/.config/fish/

ln -sf $dotfiles/nanorc ~/.nanorc

for py_version in 3.7 3.8
	if type -q python$py_version
		mkdir -p ~/.local/lib/python$py_version/site-packages/
		ln -sf $dotfiles/sitecustomize.py ~/.local/lib/python$py_version/site-packages/
	end
end

# make sure to install BeautifulDiscord using `beautifuldiscord --css ~/.config/discord/discord-custom.css`.
ln -sf $dotfiles/discord-custom.css ~/.config/discord/discord-custom.css

ln -sf $dotfiles/gitignore ~/.gitignore
git config --global core.excludesFile ~/.gitignore
